-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	Alarm_Clock_Stock = "rbxassetid://7028033435",
	Audio_Type_Icon = "rbxassetid://7028128299",
	Background = "rbxassetid://7026667770",
	Banana_Stock = "rbxassetid://7028033540",
	Book_Stock = "rbxassetid://7028033636",
	Calculator_Icon = "rbxassetid://7033021339",
	Carrot_Stock = "rbxassetid://7028033723",
	Document_Type_Icon = "rbxassetid://7029672147",
	Files_Icon = "rbxassetid://7033014552",
	LockScreen = "rbxassetid://7029546390",
	No_Icon = "rbxassetid://7028131139",
	Picture_Type_Icon = "rbxassetid://7029672179",
	Science_Stock = "rbxassetid://7028033939",
	Video_Type_Icon = "rbxassetid://7029672221",
	View_Icon = "rbxassetid://7033021388",
	Web_Icon = "rbxassetid://7033014647",
}