-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	Alarm_Clock_Stock = "rbxassetid://7028033435",
	Audio_Type_Icon = "rbxassetid://7028128299",
	Background = "rbxassetid://7026667770",
	Banana_Stock = "rbxassetid://7028033540",
	Book_Stock = "rbxassetid://7028033636",
	Carrot_Stock = "rbxassetid://7028033723",
	Documents_Type_Icon = "rbxassetid://7028131047",
	Downloads_Type_Icon = "rbxassetid://7028131086",
	Files_Icon = "rbxassetid://7026667831",
	No_Icon = "rbxassetid://7028131139",
	Pictures_Type_Icon = "rbxassetid://7028131181",
	Science_Stock = "rbxassetid://7028033939",
	Videos_Type_Icon = "rbxassetid://7028131231",
}