-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	firewatch_tower_sunrise = "rbxassetid://7025127457",
	ios_blue = "rbxassetid://7025145063",
	zelda_island = "rbxassetid://7025142713",
}